image: docker:20.10.14

stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.14-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.build:
  script:
    - IMAGE_REF="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - IMAGE_LATEST="$CI_REGISTRY_IMAGE:latest"
    - docker pull "$IMAGE_LATEST" || true
    - docker pull "$IMAGE_REF" || true
    - docker build --cache-from "$IMAGE_LATEST" --cache-from "$IMAGE_REF" --tag "$IMAGE_REF" --tag "$IMAGE_LATEST" .

# Make sure building works
build test:
  stage: test
  extends: .build
  rules:
    - if: '$CI_COMMIT_REF_NAME != "master" && $CI_COMMIT_TAG == null'


# Builds and pushes the "latest" image
build latest:
  stage: build
  extends: .build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  after_script:
    - docker push $CI_REGISTRY_IMAGE:latest

# Builds and pushes a tag image
build tag:
  stage: build
  extends: .build
  rules:
    - if: '$CI_COMMIT_TAG'
  after_script:
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
